name: test

on:
  push:
    branches:
      - master
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel:
jobs:
  # This workflow contains a single job called "test":
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Steps represent a sequence of tasks that will be executed as part of the job:
    steps:
    # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '14' # Cannot use 16 - https://github.com/npm/cli/issues/3555

    - name: Install (dev) dependencies
      run: npm install

    - name: Style test
      run: npm run lint

    - name: Build
      run: |
        mv cylc.tmLanguage.json tmLang_copy.json
        npm run build

    - name: Check grammar file matches build output
      run: diff -Z cylc.tmLanguage.json tmLang_copy.json

    - name: Unit tests
      run: npm test
